IMAGE_IDS = {
    'auth': 'AgACAgIAAxkBAAIBf2hx_eKOrbBc23W8r4fsBnPxXT44AAJs7jEb-bKRS4QCBILhi6UNAQADAgADeAADNgQ',
    'start': 'AgACAgIAAxkBAAIBgGhx_i_yPH_GUC-fY3VAdz8EjPbuAAJt7jEb-bKRS9q5SRGJi7buAQADAgADeAADNgQ',
    'about': 'AgACAgIAAxkBAAM5aIbS9qmJ8SkQ6rRhPBc7kCWOX3kAAgL4MRumQDlIjJbwVHdQ8icBAAMCAAN4AAM2BA',
    'album': 'AgACAgIAAxkBAAIBgmhx_jhBHWVFcREa84MiqGEtBA0JAAJv7jEb-bKRS0EN7tz4vWddAQADAgADeAADNgQ',
    'generation': 'AgACAgIAAxkBAAIB7WhzNT3-7oIat1K7kDusApnzIZP8AAIN9jEbKvqZS4xKgRKdkTgeAQADAgADeAADNgQ',
    'generation_error': 'AgACAgIAAxkBAAICAAFodItft2C3zpJUWp_HBna9Zs9fkgACsvsxGyr6oUu0NPhWxPzhRQEAAwIAA3gAAzYE'
}